[package]
name = "gash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
three = "0.3" # You might need to adjust this version number

[[bin]]
name = "gash"
path = "src/main.rs"

