#!/bin/bash

# This script takes three arguments: context, test_name, and status and prints them to ./master.log

if [ $# -ne 3 ]; then
    echo "Error: three arguments are required"
    exit 1
fi

context=$1
test_name=$2
status=$3
result=$(if [ $status -eq 0 ]; then echo "\-[92m✅ Succeeded\033[0m"; else echo "\e[31m❌ Failed\e[0m"; fi)
echo -e "\e[33m[[ $context ]]\e[0m\t$test_name: $result\n" >> ~/master.log
