#!/bin/bash

mkdir tests

cp ./test.ts ./main.test.ts

# Bundle TypeScript code
/root/.bun/bin/bun record_build

status=$?
../report www record_build $status

wait

/root/.bun/bin/bun test_unit

status=$?
../report www test_units $status

wait

echo "Succesfully tested."
