#!/bin/bash

curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

rustup target add wasm32-unknown-unknown && \
cargo install --force wasm-pack && \
wasm-pack build --target web

rsync -av ./pkg/ ../WASM_Assets
